# Generated by Django 4.0.3 on 2022-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_appgroup_options'),
        ('account', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apps',
            field=models.ManyToManyField(related_name='users', to='management.app'),
        ),
    ]
