# Generated by Django 4.0.3 on 2022-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='cost'),
        ),
    ]
