# Generated by Django 4.0.3 on 2022-04-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_appgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.appgroup', verbose_name='group'),
        ),
    ]
