# Generated by Django 4.0.3 on 2022-04-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_app_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.appgroup', verbose_name='group'),
        ),
    ]
