# Generated by Django 4.0.3 on 2022-05-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_appgroup_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appgroup',
            options={'verbose_name': 'App Group', 'verbose_name_plural': 'App Groups'},
        ),
    ]
