# Generated by Django 4.0.3 on 2022-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_appgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.CharField(default='default', max_length=50, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
