# Generated by Django 4.0.3 on 2022-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.ImageField(default='default', upload_to='app_images', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
