# Generated by Django 4.0.3 on 2022-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_messages_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('black', 'Black'), ('light', 'Light')], default='light', max_length=5),
        ),
    ]
