# Generated by Django 4.0.3 on 2022-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('black', 'Black'), ('bluelines', 'Blue_Lines'), ('light', 'Light')], default='light', max_length=10),
        ),
    ]
