# Generated by Django 4.0.3 on 2022-05-06 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_remove_chats_locationurl_remove_chats_token_chats_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='id',
        ),
        migrations.AddField(
            model_name='chats',
            name='locationUrl',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='chats',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
