# Generated by Django 4.0.3 on 2022-05-06 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0018_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='token',
        ),
        migrations.AddField(
            model_name='chats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(related_name='chatUser_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
