# Generated by Django 4.0.3 on 2022-05-06 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_chats_token_chats_id_alter_chats_chatusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
