# Generated by Django 4.0.3 on 2022-05-07 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0020_chats_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(blank=True, related_name='chatUser_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
