# Generated by Django 4.0.3 on 2022-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_chats_chatusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='id',
        ),
        migrations.AddField(
            model_name='chats',
            name='temp_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
