# Generated by Django 4.0.3 on 2022-05-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_remove_chats_id_chats_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='temp_id',
            new_name='id',
        ),
    ]
