# Generated by Django 4.0.3 on 2022-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_alter_chats_chatcreator_alter_chats_chatdatecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='id',
        ),
        migrations.AddField(
            model_name='messages',
            name='temp_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
