# Generated by Django 4.0.3 on 2022-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_remove_messages_id_messages_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
