# Generated by Django 4.0.3 on 2022-05-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_remove_messages_temp_id_messages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chats'),
        ),
    ]
