# Generated by Django 4.0.3 on 2022-05-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_alter_messages_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.chats'),
        ),
    ]
