# Generated by Django 4.0.3 on 2022-05-07 15:31

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_alter_messages_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.CharField(
                default='None', max_length=255, primary_key=True, serialize=False),
        ),
    ]
