# Generated by Django 4.0.3 on 2022-05-13 14:14

import client.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0031_alter_messages_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='token',
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatCreator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='chatCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatDateCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatDescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(
                related_name='chatUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='locationUrl',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(
                db_column='chat', on_delete=django.db.models.deletion.CASCADE, to='client.chats'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='chats',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
