# Generated by Django 4.0.3 on 2022-05-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0032_remove_chats_id_remove_messages_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chatCreator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatCreator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(related_name='chatUser_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
