# Generated by Django 4.0.3 on 2022-05-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0035_remove_messages_chat_delete_chats_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatDescription', models.CharField(max_length=100)),
                ('chatDateCreated', models.DateField(auto_now_add=True)),
                ('locationUrl', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chatCreator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatCreator_of', to=settings.AUTH_USER_MODEL)),
                ('chatUsers', models.ManyToManyField(related_name='chatUser_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message', models.TextField()),
                ('creator', models.TextField()),
                ('date', models.DateTimeField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(db_column='chat', on_delete=django.db.models.deletion.CASCADE, to='client.chats')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
