# Generated by Django 4.0.3 on 2022-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='id',
        ),
        migrations.AddField(
            model_name="messages",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        )

    ]
