# Generated by Django 4.0.3 on 2022-05-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0037_alter_messages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chatCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatCreator', to=settings.AUTH_USER_MODEL, verbose_name='Chat Creator'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatDateCreated',
            field=models.DateField(auto_now_add=True, verbose_name='Chat Date Created'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatDescription',
            field=models.CharField(max_length=100, verbose_name='Chat Description'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(blank=True, related_name='chatUser_of', to=settings.AUTH_USER_MODEL, verbose_name='Chat Users'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='locationUrl',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Location URL'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token'),
        ),
        migrations.AlterModelTable(
            name='chats',
            table=None,
        ),
        migrations.AlterModelTable(
            name='messages',
            table=None,
        ),
    ]
