# Generated by Django 4.0.3 on 2022-05-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_alter_chats_chatcreator_alter_chats_chatdatecreated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(db_column='chat', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.chats'),
        ),
    ]
