# Generated by Django 4.0.3 on 2022-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_alter_chats_options_alter_messages_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
