# Generated by Django 4.0.3 on 2022-05-13 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0040_chats_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(
                    default=False, verbose_name='Accepted')),
            ],
            options={
                'verbose_name': 'ChatUser',
                'verbose_name_plural': 'ChatUsers',
            },
        ),
        migrations.RemoveField(
            model_name='chats',
            name='chatUsers',
        ),
        migrations.AddField(
            model_name='chats',
            name='chatUsers',
            field=models.ManyToManyField(blank=True, related_name='chatUser_of',
                                         through='client.ChatUser', to=settings.AUTH_USER_MODEL, verbose_name='Chat Users'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='chat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='client.chats', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
