# Generated by Django 4.0.3 on 2022-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_chatuser_alter_chats_chatusers_chatuser_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='pinned',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
