# Generated by Django 4.0.3 on 2022-05-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0042_remove_chats_pinned_chatuser_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chatDateCreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chatCreator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chatDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='locationUrl',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chatUsers',
            new_name='users',
        ),
    ]
