# Generated by Django 4.0.3 on 2022-05-15 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0043_rename_chatdatecreated_chats_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='location',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chatUser_of', through='client.ChatUser', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
