# Generated by Django 4.0.3 on 2022-05-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_rename_chats_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
