# Generated by Django 4.0.3 on 2022-05-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_rename_messages_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(db_column='chat', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creator',
            field=models.TextField(verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
