# Generated by Django 4.0.3 on 2022-05-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_alter_message_options_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='client.chat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Chat Settings',
                'verbose_name_plural': 'Chat Settings',
            },
        ),
    ]
