# Generated by Django 4.0.3 on 2022-05-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0049_alter_chat_creator_alter_chatsettings_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsettings',
            name='pinned',
        ),
    ]
