# Generated by Django 3.2 on 2021-06-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('chatCreator', models.TextField()),
                ('chatUsers', models.TextField()),
                ('chatDescription', models.TextField()),
                ('chatDateCreated', models.TextField()),
                ('locationUrl', models.TextField()),
                ('token', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('message', models.TextField()),
                ('creator', models.TextField()),
                ('randompk', models.TextField(default='test', primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chats')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
