# Generated by Django 3.2 on 2021-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='randompk',
            field=models.TextField(default='test2021-06-15T21:17:53.664743+00:00', primary_key=True, serialize=False),
        ),
    ]
