# Generated by Django 3.2 on 2021-05-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210521_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chat_area',
            new_name='chatArea',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chat_creator',
            new_name='chatCreator',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chat_date_created',
            new_name='chatDateCreated',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chat_name',
            new_name='chatName',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='chat_users',
            new_name='chatUsers',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='location_url',
            new_name='locationUrl',
        ),
    ]
