# Generated by Django 3.2 on 2021-06-16 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210616_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 12, 28, 43, 839150, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
