# Generated by Django 3.2 on 2021-06-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_messages_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messageId',
            new_name='id',
        ),
    ]
