# Generated by Django 3.2 on 2021-11-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(db_column='chat', on_delete=django.db.models.deletion.CASCADE, to='client.chats'),
        ),
    ]
