# Generated by Django 4.0.3 on 2022-03-26 22:36

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(default=docs.models.Document.get_UUID4_hex, editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
